export const Languages = [
  { label: "Plain Text", value: "plaintext" },
  { label: "JavaScript", value: "javascript" },
  { label: "HTML", value: "html" },
  { label: "CSS", value: "css" },
  { label: "TypeScript", value: "typescript" },
  { label: "Python", value: "python" },
  { label: "XML", value: "xml" },
  { label: "ABAP", value: "abap" },
  { label: "Apex", value: "apex" },
  { label: "Azure CLI", value: "azcli" },
  { label: "Batch File", value: "bat" },
  { label: "Bicep", value: "bicep" },
  { label: "Cameligo", value: "cameligo" },
  { label: "Clojure", value: "clojure" },
  { label: "CoffeeScript", value: "coffeescript" },
  { label: "C", value: "c" },
  { label: "C++", value: "cpp" },
  { label: "C#", value: "csharp" },
  { label: "Content Security Policy", value: "csp" },
  { label: "Cypher", value: "cypher" },
  { label: "Dart", value: "dart" },
  { label: "Dockerfile", value: "dockerfile" },
  { label: "ECL", value: "ecl" },
  { label: "Elixir", value: "elixir" },
  { label: "Flow9", value: "flow9" },
  { label: "F#", value: "fsharp" },
  { label: "Go", value: "go" },
  { label: "GraphQL", value: "graphql" },
  { label: "Handlebars", value: "handlebars" },
  { label: "HCL", value: "hcl" },
  { label: "INI", value: "ini" },
  { label: "Java", value: "java" },
  { label: "Julia", value: "julia" },
  { label: "Kotlin", value: "kotlin" },
  { label: "LESS", value: "less" },
  { label: "Lexon", value: "lexon" },
  { label: "Lua", value: "lua" },
  { label: "M3", value: "m3" },
  { label: "Markdown", value: "markdown" },
  { label: "MDX", value: "mdx" },
  { label: "MISP", value: "misp" },
  { label: "MSDAX", value: "msdax" },
  { label: "MySQL", value: "mysql" },
  { label: "Objective-C", value: "objective-c" },
  { label: "Pascal", value: "pascal" },
  { label: "Pascaligo", value: "pascaligo" },
  { label: "Perl", value: "perl" },
  { label: "Postiats", value: "postiats" },
  { label: "Power Query", value: "powerquery" },
  { label: "PowerShell", value: "powershell" },
  { label: "Protocol Buffers", value: "proto" },
  { label: "Q#", value: "qsharp" },
  { label: "R", value: "r" },
  { label: "Razor", value: "razor" },
  { label: "Redis", value: "redis" },
  { label: "Redshift", value: "redshift" },
  { label: "reStructuredText", value: "restructuredtext" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "SB", value: "sb" },
  { label: "Scala", value: "scala" },
  { label: "Scheme", value: "scheme" },
  { label: "SCSS", value: "scss" },
  { label: "Shell", value: "shell" },
  { label: "Solidity", value: "sol" },
  { label: "AES", value: "aes" },
  { label: "SparkQL", value: "sparkql" },
  { label: "SQL", value: "sql" },
  { label: "ST", value: "st" },
  { label: "Swift", value: "swift" },
  { label: "SystemVerilog", value: "systemverilog" },
  { label: "Verilog", value: "verilog" },
  { label: "Tcl", value: "tcl" },
  { label: "Twig", value: "twig" },
  { label: "VB", value: "vb" },
  { label: "WebGPU Shader Language", value: "wgsl" },
  { label: "YAML", value: "yaml" },
  { label: "JSON", value: "json" },
];
