export const Languages = [
  { id: 1, label: "Plain Text", value: "plaintext" },
  { id: 2, label: "JavaScript", value: "javascript" },
  { id: 3, label: "HTML", value: "html" },
  { id: 4, label: "CSS", value: "css" },
  { id: 5, label: "TypeScript", value: "typescript" },
  { id: 6, label: "Python", value: "python" },
  { id: 7, label: "XML", value: "xml" },
  { id: 8, label: "ABAP", value: "abap" },
  { id: 9, label: "Apex", value: "apex" },
  { id: 10, label: "Azure CLI", value: "azcli" },
  { id: 11, label: "Batch File", value: "bat" },
  { id: 12, label: "Bicep", value: "bicep" },
  { id: 13, label: "Cameligo", value: "cameligo" },
  { id: 14, label: "Clojure", value: "clojure" },
  { id: 15, label: "CoffeeScript", value: "coffeescript" },
  { id: 16, label: "C", value: "c" },
  { id: 17, label: "C++", value: "cpp" },
  { id: 18, label: "C#", value: "csharp" },
  { id: 19, label: "Content Security Policy", value: "csp" },
  { id: 20, label: "Cypher", value: "cypher" },
  { id: 21, label: "Dart", value: "dart" },
  { id: 22, label: "Dockerfile", value: "dockerfile" },
  { id: 23, label: "ECL", value: "ecl" },
  { id: 24, label: "Elixir", value: "elixir" },
  { id: 25, label: "Flow9", value: "flow9" },
  { id: 26, label: "F#", value: "fsharp" },
  { id: 27, label: "Go", value: "go" },
  { id: 28, label: "GraphQL", value: "graphql" },
  { id: 29, label: "Handlebars", value: "handlebars" },
  { id: 30, label: "HCL", value: "hcl" },
  { id: 31, label: "INI", value: "ini" },
  { id: 32, label: "Java", value: "java" },
  { id: 33, label: "Julia", value: "julia" },
  { id: 34, label: "Kotlin", value: "kotlin" },
  { id: 35, label: "LESS", value: "less" },
  { id: 36, label: "Lexon", value: "lexon" },
  { id: 37, label: "Lua", value: "lua" },
  { id: 38, label: "M3", value: "m3" },
  { id: 39, label: "Markdown", value: "markdown" },
  { id: 40, label: "MDX", value: "mdx" },
  { id: 41, label: "MISP", value: "misp" },
  { id: 42, label: "MSDAX", value: "msdax" },
  { id: 43, label: "MySQL", value: "mysql" },
  { id: 44, label: "Objective-C", value: "objective-c" },
  { id: 45, label: "Pascal", value: "pascal" },
  { id: 46, label: "Pascaligo", value: "pascaligo" },
  { id: 47, label: "Perl", value: "perl" },
  { id: 48, label: "Postiats", value: "postiats" },
  { id: 49, label: "Power Query", value: "powerquery" },
  { id: 50, label: "PowerShell", value: "powershell" },
  { id: 51, label: "Protocol Buffers", value: "proto" },
  { id: 52, label: "Q#", value: "qsharp" },
  { id: 53, label: "R", value: "r" },
  { id: 54, label: "Razor", value: "razor" },
  { id: 55, label: "Redis", value: "redis" },
  { id: 56, label: "Redshift", value: "redshift" },
  { id: 57, label: "reStructuredText", value: "restructuredtext" },
  { id: 58, label: "Ruby", value: "ruby" },
  { id: 59, label: "Rust", value: "rust" },
  { id: 60, label: "SB", value: "sb" },
  { id: 61, label: "Scala", value: "scala" },
  { id: 62, label: "Scheme", value: "scheme" },
  { id: 63, label: "SCSS", value: "scss" },
  { id: 64, label: "Shell", value: "shell" },
  { id: 65, label: "Solidity", value: "sol" },
  { id: 66, label: "AES", value: "aes" },
  { id: 67, label: "SparkQL", value: "sparkql" },
  { id: 68, label: "SQL", value: "sql" },
  { id: 69, label: "ST", value: "st" },
  { id: 70, label: "Swift", value: "swift" },
  { id: 71, label: "SystemVerilog", value: "systemverilog" },
  { id: 72, label: "Verilog", value: "verilog" },
  { id: 73, label: "Tcl", value: "tcl" },
  { id: 74, label: "Twig", value: "twig" },
  { id: 75, label: "VB", value: "vb" },
  { id: 76, label: "WebGPU Shader Language", value: "wgsl" },
  { id: 77, label: "YAML", value: "yaml" },
  { id: 78, label: "JSON", value: "json" },
];
